#ifndef CMOS_IOCTL
#define CMOS_IOCTL

#define DRIVER_SUCCESS 0x25

#define DRIVER_NAME TEXT("cmosrw")
#define DRIVER_PATH TEXT("\\\\.\\cmosrw")

#define IOCTL_TYPE 40000

#define IOCTL_READ_CMOS \
    CTL_CODE( IOCTL_TYPE, 0x902, METHOD_BUFFERED, FILE_ANY_ACCESS  )

#define IOCTL_WRITE_CMOS \
    CTL_CODE( IOCTL_TYPE, 0x903, METHOD_BUFFERED, FILE_ANY_ACCESS  )

#endif